import Navbar from "../../../../components/layout/Navbar";
import NavbarDashboard from "../../../../components/layout/dashboard/NavbarDashboard";
import Sidebar from "../../../../components/layout/sidebar/Sidebar";
import "../../globals.css";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <section className="flex">
          <Sidebar />
          <section className="w-full">
            <NavbarDashboard />
            {children}
          </section>

        </section>

      </body>
    </html>
  )
}
