import NavbarDashboard from "../../../../components/layout/dashboard/NavbarDashboard";
import Sidebar from "../../../../components/layout/sidebar/Sidebar";
import "../../globals.css";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="fa">
      <body>
        <section className="flex">
          <Sidebar />
          <section className="w-[86%] h-screen overflow-y-auto ">
            <NavbarDashboard />
            <section className='max-w-[1440px] p-4 pt-28 '>
              {children}
            </section>
          </section>
        </section>
      </body>
    </html>
  )
}
