import Navbar from "../../components/layout/Navbar";
import "./globals.css";
import '../../components/Embla/css/embla.css';

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="fa">
            <body>
                <Navbar />
                {children}
            </body>
        </html>
    );
}
