import Navbar from "../../components/layout/Navbar";
import "./globals.css";
import '../../components/Embla/css/embla.css';
import Footer from "../../components/layout/Footer";
import ContactUsFooter from "../../components/layout/ContactUsFooter";
import Blue from "../../components/layout/Blue";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa">
      <body className="home-bg">
        <Navbar />
        <section className="w-[1440px] m-auto px-4">
          {children}
          <ContactUsFooter />
          <Blue />
          <Footer />
        </section>
      </body>
    </html>
  );
}
