import Navbar from "../../components/layout/Navbar";
import "./globals.css";
import '../../components/Embla/css/embla.css';
import Footer from "../../components/layout/Footer";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
      <html lang="fa">
        <body className="home-bg">
          <Navbar />
          <section  className="w-[1440px] m-auto px-4">{children}</section>
        </body>
      </html>
    );
}
